/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-19 22:55:47
*/

package com.silvera.SciPaper.service.base;

import org.springframework.stereotype.Service;
import com.silvera.SciPaper.domain.model.*;
import com.silvera.SciPaper.messages.*;
import org.springframework.beans.factory.annotation.Autowired;


public interface ISciPaperService {

    // Auto-generated CRUD methods
    
    
    
    public Paper createPaper(Paper paper);
    
    
    public Paper updatePaper(java.lang.String id, Paper paperUpdate);
    
    
    public Paper readPaper(java.lang.String id);
    
    
    public void deletePaper(java.lang.String id);
    
    

    
    public java.util.List<Paper> getAllByAuthor(java.lang.String authorId);
    
    public void publish(java.lang.String paperId, String authorId);
    

    

}