/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-19 16:57:01
*/

package com.silvera.SciPaper.repository;

import java.util.List;

import com.silvera.SciPaper.domain.model.Paper;
import org.springframework.data.mongodb.repository.MongoRepository;


public interface PaperRepository extends MongoRepository<Paper, java.lang.String> {
  // CRUD operations are included in MongoRepository interface
  List<Paper> getAllByAuthorId(java.lang.String authorId);
}