/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-19 22:55:47
*/

package com.silvera.User.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;
import javax.validation.Valid;

import com.silvera.User.service.base.IUserService;
import com.silvera.User.domain.model.*;
import com.silvera.User.dto.LoginRequest;


@RefreshScope
@RestController
public class UserController {

    @Autowired
    IUserService userService;

    // Auto-generated CRUD methods
    
    
    @RequestMapping(value="/register", method=RequestMethod.POST)
    @ResponseBody
    public User createUser(@Valid @RequestBody User user){
        return userService.createUser(user);
    }
    
    
    @RequestMapping(value="/user/{id}", method=RequestMethod.GET)
    @ResponseBody
    public User readUser(@PathVariable java.lang.String id){
        return userService.readUser(id);
    }
    
    
    @PostMapping(value = "/auth")
    @ResponseBody
    public java.lang.String authenticate(@RequestBody LoginRequest login) {
        return userService.authenticate(login.username, login.password);
    }


    @GetMapping(value="isloggedin/{token}")
    @ResponseBody
    public java.lang.Boolean isLoggedIn(@PathVariable java.lang.String token) {
        return userService.isLoggedIn(token);
    }


    @GetMapping(value="getname/{token}")
    @ResponseBody
    public java.lang.String getName(@PathVariable java.lang.String token) {
        return userService.getName(token);
    }

}