/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-19 22:55:47
*/

package com.silvera.User.service.base;

import com.silvera.User.domain.model.*;


public interface IUserService {

    // Auto-generated CRUD methods
    
    
    
    public User createUser(User user);
    
    
    
    public User readUser(java.lang.String id);
    
    
    


    
     
    
    public java.lang.String authenticate(java.lang.String username, java.lang.String password) ;
    
     
    
    public java.lang.Boolean isLoggedIn(java.lang.String token) ;
    
     
    
    public java.lang.String getName(java.lang.String token) ;
    

}