/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-19 16:57:01
*/

package com.silvera.User.repository;

import java.util.Optional;

import com.silvera.User.domain.model.User;
import org.springframework.data.mongodb.repository.MongoRepository;


public interface UserRepository extends MongoRepository<User, java.lang.String> {
  // CRUD operations are included in MongoRepository interface
  Optional<User> findByUsername(java.lang.String username);
}